FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

ENV NODE_ENV=development

RUN npm install && \
    chmod -R 755 node_modules/.bin

COPY . .

RUN chown -R node:node /app

USER node

EXPOSE 5000

CMD ["npm", "run", "dev"]
